services:
  app:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    command: sleep infinity
    volumes:
      - ..:/workspaces/workspace:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
